const data ={
    projects: [
        {
            name:'הבלונים 24', 
            year: '2017',
            size:'100',
            category:'שיפוץ דירה',
            description:'דירת קבלן בבניין מגורים בשכונת פארק תל אביב, שבעזרת עבודת שיפוץ ונגרות חכמה הצלחנו לנצל את השטח עד תום, הגדלנו משמעותית את מקומות האכסון והדירה הפכה למרווחת ונעימה למגורים',
            country:'ישראל',
            city:'תל אביב',
            cardUrl:'/images/projects/recent/1.jpg',
            cardAlt: 'תמונה של הנכס לכרטיס הפרוייקט',
            urlPamorama:'/images/projects/recent/2.jpg',
            altPamorama:'תמונה של הנכס מבחוץ',
            urlBefore:'/images/projects/recent/3.jpg',
            altBefore:'תמונה של הנכס לפני הבנייה/ שיפוץ',
            desBefore:'בלה בלה',
            urlSketch:'/images/projects/recent/4.jpg',
            altSketch:'הסקיצה של הפרוייקט',
            desSketch:'בלה בלה',
            urlImaging:'/images/projects/recent/5.jpg',
            altImaging:'הדמייה של הפרוייקט',
            desImaging:'בלה בלה',
            urlConstraction:'/images/projects/recent/1.jpg',
            altConstraction:'תמונה מהבנייה/ השיפוץ',
            desConstraction:'בלה בלה',
            urlGallery:'/images/projects/recent/2.jpg',
            altGallery:'תמונה של הנכס לגלריית התמונות'
        },
        {
            name:'שמואל תמיר 47', 
            year: '2016',
            size:'110',
            category:'שיפוץ דירה',
            description:'דירת קבלן בבניין מגורים בשכונת בצפון החדש של תל אביב, שבעזרת עבודת שיפוץ ונגרות חכמה הצלחנו לנצל את        השטח עד תום, הגדלנו משמעותית את מקומות האכסון והדירה הפכה למרווחת ונעימה למגורים',
            country:'ישראל',
            city:'תל אביב',
            cardUrl:'/images/projects/recent/2.jpg',
            cardAlt: 'תמונה של הנכס לכרטיס הפרוייקט',
            urlPamorama:'/images/projects/recent/3.jpg',
            altPamorama:'תמונה של הנכס מבחוץ',
            urlBefore:'/images/projects/recent/4.jpg',
            altBefore:'תמונה של הנכס לפני הבנייה/ שיפוץ',
            desBefore:'בלה בלה',
            urlSketch:'/images/projects/recent/5.jpg',
            altSketch:'הסקיצה של הפרוייקט',
            desSketch:'בלה בלה',
            urlImaging:'/images/projects/recent/1.jpg',
            altImaging:'הדמייה של הפרוייקט',
            desImaging:'בלה בלה',
            urlConstraction:'/images/projects/recent/2.jpg',
            altConstraction:'תמונה מהבנייה/ השיפוץ',
            desConstraction:'בלה בלה',
            urlGallery:'/images/projects/recent/3.jpg',
            altGallery:'תמונה של הנכס לגלריית התמונות'
        },
        {
            name:'  הכלנית 24', 
            year: '2020',
            size:'75',
            category:'שיפוץ דירה',
            description:'דירת קבלן בבניין מגורים בהוד השרון, שבעזרת עבודת שיפוץ ונגרות חכמה הצלחנו לנצל את השטח עד תום,         הגדלנו משמעותית את מקומות האכסון והדירה הפכה למרווחת ונעימה למגורים',
            country:'ישראל',
            city:'הוד השרון',
            cardUrl:'/images/projects/recent/3.jpg',
            cardAlt: 'תמונה של הנכס לכרטיס הפרוייקט',
            urlPamorama:'/images/projects/recent/4.jpg',
            altPamorama:'תמונה של הנכס מבחוץ',
            urlBefore:'/images/projects/recent/5.jpg',
            altBefore:'תמונה של הנכס לפני הבנייה/ שיפוץ',
            desBefore:'בלה בלה',
            urlSketch:'/images/projects/recent/1.jpg',
            altSketch:'הסקיצה של הפרוייקט',
            desSketch:'בלה בלה',
            urlImaging:'/images/projects/recent/2.jpg',
            altImaging:'הדמייה של הפרוייקט',
            desImaging:'בלה בלה',
            urlConstraction:'/images/projects/recent/3.jpg',
            altConstraction:'תמונה מהבנייה/ השיפוץ',
            desConstraction:'בלה בלה',
            urlGallery:'/images/projects/recent/4.jpg',
            altGallery:'תמונה של הנכס לגלריית התמונות'
        },
        {
            name:'סוקולוב 2', 
            year: '2016',
            size:'100',
            category:'שיפוץ דירה',
            description:'דירת קבלן בבניין מגורים ברמת גן, שבעזרת עבודת שיפוץ ונגרות חכמה הצלחנו לנצל את השטח עד תום, הגדלנו         משמעותית את מקומות האכסון והדירה הפכה למרווחת ונעימה למגורים',
            country:'ישראל',
            city:'רמת גן',
            cardUrl:'/images/projects/recent/4.jpg',
            cardAlt: 'תמונה של הנכס לכרטיס הפרוייקט',
            urlPamorama:'/images/projects/recent/5.jpg',
            altPamorama:'תמונה של הנכס מבחוץ',
            urlBefore:'/images/projects/recent/1.jpg',
            altBefore:'תמונה של הנכס לפני הבנייה/ שיפוץ',
            desBefore:'בלה בלה',
            urlSketch:'/images/projects/recent/2.jpg',
            altSketch:'הסקיצה של הפרוייקט',
            desSketch:'בלה בלה',
            urlImaging:'/images/projects/recent/3.jpg',
            altImaging:'הדמייה של הפרוייקט',
            desImaging:'בלה בלה',
            urlConstraction:'/images/projects/recent/4.jpg',
            altConstraction:'תמונה מהבנייה/ השיפוץ',
            desConstraction:'בלה בלה',
            urlGallery:'/images/projects/recent/5.jpg',
            altGallery:'תמונה של הנכס לגלריית התמונות'
        },
    ],

    resumes:[
        {
            title: "רחלי יכין",
            subTitle: "ארכיטקטית ומעצבת פנים",
            profileUrl: '/images/theTeam/racheli.png',
            profileAlt: 'תמונת פרופיל של רחלי',
            firstP: 'בוגרת תואר ראשון באדריכלות באקדמיה לעיצוב ואומנות "בצלאל". במהלך לימודי נבחרתי לייצג את הסטודיו ולפתח מרכז מבקרים לקהילה הטיפולית לגמילה בסמים "אילנות". כמו כן נשלחתי להשתתף בסדנת אורח של האדריכל... בברלין וכן נבחרתי להשתתף ב "סטודיו ניו -יורק" ששיתפה פעולה עם עיריית ניו יורק לביצוע פרויקט אדריכלי בעיר. ',
            secondp: 'בתום לימודי הועסקתי כאדריכלית במשרד האדריכלים "רני זיס אדריכלים". במסגרת עבודתי עיצבתי פרויקטים אדריכליים גדולים ברחבי העולם שכללו בין היתר: בתי מלון, וילות יוקרתיות, שכונות מגורים, מתחמי דירות ובנייני דירות רבי קומות.' ,
            thirdP:'במקביל ובאופן עצמאי, עסקתי בקנייה, שיפוץ ומכירת  8 דירות מגורים ושתי וילות, שהתשואה מהעסקאות לאחר השבחת הנכסים נעה בין 10%-25% .',
            fourthP:'כיום, כאחת מהבעלים של חברת "אנו אדריכלים" וכאדריכלית ראשית בחברה אני מביאה לידי ביטוי את כל יכולותיי בתחומי האדריכלות, העיצוב והנדלן השונים. אני שמחה להיות חלק מחברה שאפתנית הלוקחת פרויקט משלב הקונספט וגורמת לרעיון לרקום עור וגידים  ',
        },
        {
            title: "רעות פדל אבינדב",
            subTitle: "ארכיטקטית ומעצבת פנים",
            profileUrl: '/images/theTeam/reut.png',
            profileAlt: 'תמונת פרופיל של רעות פדל אבינדב',
            firstP: 'בוגרת תואר ראשון  B.Arch.ed באדריכלות באקדמיה לעיצוב וחינוך ויצו חיפה. במהלך לימודי הועסקתי כאסיסטנטית  בסטודיו תכנון אדריכלי שנה א. כמו כן השתתפתי בקורסים עם האדריכל הקטלוני Josep M Botey, ת"א/חיפה, בסדנת שילוב ופתיחות חברתית - תכנון לאנשים עם מוגבלויות באוניברסיטת ת"א ובפרויקט REMPART - לימוד טכניקות שונות של שימור  בברזי לה סק, צרפת.',
            
            secondp: 'בתום לימודי הועסקתי כאדריכלית במשרד האדריכלים "רני זיס אדריכלים". במסגרת עבודתי כאדריכלית וראש צוות הובלתי פרויקטים אדריכליים, פרויקטים ותחרויות בקנה מידה שונים. הייתי  אחראית על תכנון משלב הקונספט ,ניתוח זכויות, הכנת תב"עות, פיתוח והכנת פרוגרמה, הגשות להיתר, עבודה מול הרשויות, תוכניות למכרז, תוכניות לביצוע כולל שרטוט פרטי בניין, תיאום יועצים מלא ועד לפיקוח בשלב הביצוע. ' ,
            thirdP:'במקביל ובאופן עצמאי, תכננתי וליוויתי ופיקחתי את ביצועם של מספר פרויקטים בקני מידה שונים: עיצוב חללי עבודה, שיפוץ ובנייה פרטית , ליווי תמ"א 38 ותכנון מבני מסחר. במקביל אני ממשיכה להגיש לתחרויות באופן עצמי מתוך הרצון לשוט קדימה ולהוביל. ',
            fourthP:'כיום, משמשת כשותפה במשרד "אנו אדריכלים" מטרתנו במשרד הוא ליצור אדריכלות יפה, מותאמת ,ירוקה ופונקציונלית למשתמש מתוך הידיעה כי המבנים שלנו יישארו הרבה אחרינו. ברמה האישית, אני חושבת שסיבה העיקרית שבה בחרתי לעסוק באדריכלות היא, היכולת ליצור. לראות איך פרויקט מגיע משלב הקונספט אל מבנה קיים. ',
        },
        {
            title: "אלי בן גיגי",
            subTitle: "מנהל פרוייקט בנייה",
            profileUrl: '/images/theTeam/ali.png',
            profileAlt: 'תמונת פרופיל של אלי בן גיגי',
            firstP: 'בוגרת תואר ראשון באדריכלות באקדמיה לעיצוב ואומנות "בצלאל". במהלך לימודי נבחרתי לייצג את הסטודיו ולפתח מרכז מבקרים לקהילה הטיפולית לגמילה בסמים "אילנות". כמו כן נשלחתי להשתתף בסדנת אורח של האדריכל... בברלין וכן נבחרתי להשתתף ב "סטודיו ניו -יורק" ששיתפה פעולה עם עיריית ניו יורק לביצוע פרויקט אדריכלי בעיר. ',
            secondp: 'בתום לימודי הועסקתי כאדריכלית במשרד האדריכלים "רני זיס אדריכלים". במסגרת עבודתי עיצבתי פרויקטים אדריכליים גדולים ברחבי העולם שכללו בין היתר: בתי מלון, וילות יוקרתיות, שכונות מגורים, מתחמי דירות ובנייני דירות רבי קומות.' ,
            thirdP:'במקביל ובאופן עצמאי, עסקתי בקנייה, שיפוץ ומכירת  8 דירות מגורים ושתי וילות, שהתשואה מהעסקאות לאחר השבחת הנכסים נעה בין 10%-25% .',
            fourthP:'כיום, כאחת מהבעלים של חברת "אנו אדריכלים" וכאדריכלית ראשית בחברה אני מביאה לידי ביטוי את כל יכולותיי בתחומי האדריכלות, העיצוב והנדלן השונים. אני שמחה להיות חלק מחברה שאפתנית הלוקחת פרויקט משלב הקונספט וגורמת לרעיון לרקום עור וגידים  ',
        },
    ],

    blogs:[
        {
            title: "מאמר בנושא ארכיטקטורה",
            subTitle: "כותרת משנה של מאמר בנושא ארכיטקטורה",
            author: "דוד יכין",
            category: "בניינים",
            cardUrl: '/images/blog/4.jpg',
            cardAlt: 'תמונה לכרטיס המאמר',
            titleImgUrl: "/images/blog/5.jpg",
            titleImgAlt: "בלה בלה",
            titleImgCredit: "דוד יכין",
            endImgUrl: "/images/blog/2.jpg",
            endImgAlt: "בלה בלה",
            endImgCredit: "דוד יכין",
            firstInnerTitle: "בלה בלה",
            firstP:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum...",
            secondP: "הוא פשוט טקסט גולמי של תעשיית ההדפסה וההקלדה. Lorem Ipsum היה טקסט סטנ...", 
            thirdP: " הולך להשתמש במקטעים של של Lorem Ipsum אתה צריך להיות בטוח שאין משהו מ...",
            landscapeImgUrl: "/images/blog/1.jpg",
            landscapeImgAlt: "בלה בלה",
            landscapeImgCredit: "דוד יכין",
            secondInnerTitle: "כותרת שנייה בגוף המאמר",
            foruthP: "הפסקאות הסטנדרטיות של Lorem Ipsum שהיו בשימוש מאז המאה ה-16 משוחזרות ב...",
            fifthP: "לקים מתוך הספרות הלטינית הקלאסית מאז 45 לפני הספירה. מה שהופך אותו לעת...",
            sixthP: "לקים מתוך הספרות הלטינית הקלאסית מאז 45 לפני הספירה. מה שהופך אותו לעת...",
            profileImgUrl: "/images/blog/4.jpg",
            profileImgAlt: "בלה בלה",
            profileImgCredit: "דוד יכין",
            thirdInnerTitle: "כותרת שלישית בגוף המאמר",
            seventhP: "הפסקאות הסטנדרטיות של Lorem Ipsum שהיו בשימוש מאז המאה ה-16 משוחזרות ב...",
            eighthP: "והי עובדה מבוססת שדעתו של הקורא תהיה מוסחת על ידי טקטס קריא כאשר הוא י...", 
            ninthP:"ם אתה הולך להשתמש במקטעים של של Lorem Ipsum אתה צריך להיות בטוח שאין מ..."
        },
        {
            title: "מאמר בנושא ניהול פרוייקט בנייה",
            subTitle: "כותרת משנה של מאמר בנושא ניהול פרוייקט בנייה",
            author: "דוד יכין",
            category: "בניינים",
            cardUrl: '/images/blog/3.jpg',
            cardAlt: 'תמונה לכרטיס המאמר',
            titleImgUrl: "/images/blog/5.jpg",
            titleImgAlt: "בלה בלה",
            titleImgCredit: "דוד יכין",
            endImgUrl: "/images/blog/2.jpg",
            endImgAlt: "בלה בלה",
            endImgCredit: "דוד יכין",
            firstInnerTitle: "בלה בלה",
            firstP:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum...",
            secondP: "הוא פשוט טקסט גולמי של תעשיית ההדפסה וההקלדה. Lorem Ipsum היה טקסט סטנ...", 
            thirdP: " הולך להשתמש במקטעים של של Lorem Ipsum אתה צריך להיות בטוח שאין משהו מ...",
            landscapeImgUrl: "/images/blog/1.jpg",
            landscapeImgAlt: "בלה בלה",
            landscapeImgCredit: "דוד יכין",
            secondInnerTitle: "כותרת שנייה בגוף המאמר",
            foruthP: "הפסקאות הסטנדרטיות של Lorem Ipsum שהיו בשימוש מאז המאה ה-16 משוחזרות ב...",
            fifthP: "לקים מתוך הספרות הלטינית הקלאסית מאז 45 לפני הספירה. מה שהופך אותו לעת...",
            sixthP: "לקים מתוך הספרות הלטינית הקלאסית מאז 45 לפני הספירה. מה שהופך אותו לעת...",
            profileImgUrl: "/images/blog/4.jpg",
            profileImgAlt: "בלה בלה",
            profileImgCredit: "דוד יכין",
            thirdInnerTitle: "כותרת שלישית בגוף המאמר",
            seventhP: "הפסקאות הסטנדרטיות של Lorem Ipsum שהיו בשימוש מאז המאה ה-16 משוחזרות ב...",
            eighthP: "והי עובדה מבוססת שדעתו של הקורא תהיה מוסחת על ידי טקטס קריא כאשר הוא י...", 
            ninthP:"ם אתה הולך להשתמש במקטעים של של Lorem Ipsum אתה צריך להיות בטוח שאין מ..."
        },
        {
            title: "מאמר בנושא עיצוב פנים",
            subTitle: "כותרת משנה של מאמר בנושא עיצוב פנים",
            author: "דוד יכין",
            category: "בניינים",
            cardUrl: '/images/blog/2.jpg',
            cardAlt: 'תמונה לכרטיס המאמר',
            titleImgUrl: "/images/blog/5.jpg",
            titleImgAlt: "בלה בלה",
            titleImgCredit: "דוד יכין",
            endImgUrl: "/images/blog/2.jpg",
            endImgAlt: "בלה בלה",
            endImgCredit: "דוד יכין",
            firstInnerTitle: "בלה בלה",
            firstP:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum...",
            secondP: "הוא פשוט טקסט גולמי של תעשיית ההדפסה וההקלדה. Lorem Ipsum היה טקסט סטנ...", 
            thirdP: " הולך להשתמש במקטעים של של Lorem Ipsum אתה צריך להיות בטוח שאין משהו מ...",
            landscapeImgUrl: "/images/blog/1.jpg",
            landscapeImgAlt: "בלה בלה",
            landscapeImgCredit: "דוד יכין",
            secondInnerTitle: "כותרת שנייה בגוף המאמר",
            foruthP: "הפסקאות הסטנדרטיות של Lorem Ipsum שהיו בשימוש מאז המאה ה-16 משוחזרות ב...",
            fifthP: "לקים מתוך הספרות הלטינית הקלאסית מאז 45 לפני הספירה. מה שהופך אותו לעת...",
            sixthP: "לקים מתוך הספרות הלטינית הקלאסית מאז 45 לפני הספירה. מה שהופך אותו לעת...",
            profileImgUrl: "/images/blog/4.jpg",
            profileImgAlt: "בלה בלה",
            profileImgCredit: "דוד יכין",
            thirdInnerTitle: "כותרת שלישית בגוף המאמר",
            seventhP: "הפסקאות הסטנדרטיות של Lorem Ipsum שהיו בשימוש מאז המאה ה-16 משוחזרות ב...",
            eighthP: "והי עובדה מבוססת שדעתו של הקורא תהיה מוסחת על ידי טקטס קריא כאשר הוא י...", 
            ninthP:"ם אתה הולך להשתמש במקטעים של של Lorem Ipsum אתה צריך להיות בטוח שאין מ..."
        },
    ],
    users: [
        {
            name: "admin",
            lastName: "admin", 
            email: "admin@gmail.com",
            phone: "0507233332",
            password: "$2b$10$wtmDgFgnTq7cmEn.yGjGXeme34WT91B7RDRPWgOb4Q9KFguCMaiLy",
            admin: true,
            isBloger:true
        }
    ]
}

exports.data = data;